# Generated by Django 3.1.7 on 2021-05-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210525_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='specialty',
        ),
    ]
