# Generated by Django 3.1.7 on 2021-05-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20210526_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialty',
            old_name='name',
            new_name='SpecialtyName',
        ),
    ]
