# Generated by Django 3.1.7 on 2021-05-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20210526_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='mark',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
