# Generated by Django 3.1.7 on 2021-05-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20210526_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='averageMark',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
