# Generated by Django 3.1.7 on 2021-05-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20210526_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='averageMark',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(to='students.Student'),
        ),
    ]
