# Generated by Django 3.1.7 on 2021-05-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20210526_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='averageMark',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
