# Generated by Django 3.1.7 on 2021-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20210526_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='averageMark',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
