# Generated by Django 3.1.7 on 2021-05-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='averageMark',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
