# Generated by Django 3.1.7 on 2021-05-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20210526_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('specialty',)},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='averageMark',
        ),
    ]
